compacts code

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -77,15 +77,10 @@ deploy:
     - chmod +x ./kubectl
     - mv ./kubectl /usr/local/bin/kubectl
     - 'wget -O deploy.sh "${URL_DEPLOY_SH}"'
-    - echo "--no-cache --no-cookies was not used by wget"
-    - if [ ! -f deploy.sh ];
-        then echo "k8s deployment file is missing";
-      fi
     - 'wget -O wp-config-template.yml "${URL_WP_CONFIG_TEMPLATE_yml}"'
     - echo "--no-cache --no-cookies was not used by wget"
-    - if [ ! -f wp-config-template.yml ];
-        then echo "k8s config file is missing";
-      fi
+    - if [ ! -f deploy.sh ]; then echo "k8s deployment file is missing"; exit 1; fi
+    - if [ ! -f wp-config-template.yml ]; then echo "k8s config file is missing"; exit 1; fi
     - chmod +x deploy.sh
   script:
     - ./deploy.sh HX pepvep-fe pepvep # fallback app_name namespace
